### ISSUE TITLE
Error trying to emulate ios or run on ios device

### ISSUE THREAD

**Issue by DennisM330** [Jakeeyturner/composer-ionic#10]
Nice job, the app runs fine using npm start or ionic serve

Trying to emulate on ios or running on ios gets a Channel Closed error. Can ignore the Lint messages below. The same Channel Closed error occurs for Android too.

ionic cordova run ios
Running app-scripts build: --address 0.0.0.0 --port 8100 --p 8100 --livereload-port 35729 --r 35729 --iscordovaserve --nobrowser

[16:19:16]  build dev started ... 
[16:19:16]  clean started ... 
[16:19:16]  clean finished in 5 ms 
[16:19:16]  copy started ... 
[16:19:16]  deeplinks started ... 
[16:19:17]  deeplinks finished in 218 ms 
[16:19:17]  transpile started ... 
[16:19:21]  transpile finished in 3.93 s 
[16:19:21]  preprocess started ... 
[16:19:21]  preprocess finished in less than 1 ms 
[16:19:21]  webpack started ... 
[16:19:21]  copy finished in 4.29 s 
[16:19:27]  webpack finished in 6.70 s 
[16:19:27]  sass started ... 
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
[16:19:28]  sass finished in 1.06 s 
[16:19:28]  postprocess started ... 
[16:19:28]  postprocess finished in 5 ms 
[16:19:28]  lint started ... 
[16:19:28]  build dev finished in 12.04 s 
[WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova). Your plugins may be out of
       date.
TypeError: env.runcmd is not a function

MacBook-Pro-28:DigitalPartsProvenanceMobile drmiller$ [16:19:31]  tslint: src/app/app.module.ts, line: 26 
            'ORG_HYPERLEDGER_COMPOSER_SYSTEM' is declared but never used. 

      L26:  import * as ORG_HYPERLEDGER_COMPOSER_SYSTEM from './org.hyperledger.composer.system';
      L27:  import * as NET_BIZ_DIGITALPARTSNETWORK from './net.biz.digitalpartsnetwork';

[16:19:31]  tslint: src/app/app.module.ts, line: 27 
            'NET_BIZ_DIGITALPARTSNETWORK' is declared but never used. 

      L26:  import * as ORG_HYPERLEDGER_COMPOSER_SYSTEM from './org.hyperledger.composer.system';
      L27:  import * as NET_BIZ_DIGITALPARTSNETWORK from './net.biz.digitalpartsnetwork';

(node:18856) UnhandledPromiseRejectionWarning: Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at process.target.send (internal/child_process.js:588:16)
    at taskError (/Users/drmiller/Desktop/digitalpartsnetwork/apps/DigitalPartsProvenanceMobile/node_modules/@ionic/app-scripts/dist/worker-process.js:57:13)
    at /Users/drmiller/Desktop/digitalpartsnetwork/apps/DigitalPartsProvenanceMobile/node_modules/@ionic/app-scripts/dist/worker-process.js:17:13
    at <anonymous>
(node:18856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by DennisM330** [comment]
This seems to help to rid of the channel closed error
npm uninstall --save-dev @ionic/cli-plugin-cordova
npm install --save-dev @ionic/cli-plugin-cordova@1.4.1

See https://github.com/ionic-team/ionic/issues/12561

**Comment by Jakeeyturner** [comment]
Hi @DennisM330 

I haven't been able to run iOS applications due to my development environment, so thank you for creating this issue!

Would you be able to clarify which package you had to uninstall and re-install for iOS to work correctly?

Thanks,
Jake

**Comment by DennisM330** [comment]
npm uninstall --save-dev @ionic/cli-plugin-cordova
npm install --save-dev @ionic/cli-plugin-cordova@1.4.1

After I did that, I can both run on my iPad or use the cordova ios emulator.

**Comment by DennisM330** [comment]
Copy/paste not working. Should be “@ionic/cli_cordova_plugin” for the uninstall. Add @1.4.1 at the end for the install

**Comment by DennisM330** [comment]
[package.txt](https://github.com/Jakeeyturner/composer-ionic/files/2033071/package.txt)

**Comment by DennisM330** [comment]
I am fully functional now (both ios emulator and running app on my iPad) after just simply staying with the cli cordova plugin version referenced above. Might want to check with ionic to see if there is an issue with later versions of the plugin. Probably not a bug here but maybe an ionic dependancy.

**Comment by DennisM330** [comment]
For reference, I had to perform some other updates on my Mac to deploy the app to my iOS devices including xcode and ios-deploy, Ionic Info now shows:
ionic info
[WARN] Detected locally installed Ionic CLI, but it's too old--using global CLI.

cli packages: (/Users/drmiller/.nvm/versions/node/v8.11.1/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.7.1

System:

    ios-deploy : 1.9.2 
    ios-sim    : 5.0.8 
    Node       : v8.11.1
    npm        : 5.6.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3.1 Build version 9E501 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by Jakeeyturner** [comment]
Thanks @DennisM330 

Would you be able to clone this repository and test the new changes I've made for iOS?

Also, if you don't mind and have the time, would you be able to create a guide for configuring your iOS development environment?

**Comment by Jakeeyturner** [comment]
Thank you @DennisM330!
I'm going to include these instructions in the repositories README.

- Jake

**Comment by DennisM330** [comment]
May want to consider adding these version pre-reqs for MacOS High Sierra
ios-deploy : 1.9.2 
OS         : macOS High Sierra
Xcode      : Xcode 9.3.1 Build version 9E501
